### ISSUE TITLE
Issue when running 

### ISSUE THREAD

**Issue by ankeborg** [axsddlr/TCCR#1]
Unable to retrieve the user ID for **REDACTED** 'data'
Couldn't create clip. can only concatenate str (not "NoneType") to str

**Comment by axsddlr** [comment]
> Unable to retrieve the user ID for **REDACTED** 'data'
> Couldn't create clip. can only concatenate str (not "NoneType") to str

need to make a .env file with your own twitch client id and token with ability to clip channel for this to work
hence why this is here:

https://github.com/axsddlr/TCCR/blob/master/.env.example

**Comment by ankeborg** [comment]
> > Unable to retrieve the user ID for **REDACTED** 'data'
> > Couldn't create clip. can only concatenate str (not "NoneType") to str
> 
> need to make a .env file with your own twitch client id and token with ability to clip channel for this to work
> hence why this is here:
> 
> https://github.com/axsddlr/TCCR/blob/master/.env.example

Thank you, issue fixed.

**Comment by axsddlr** [comment]
let me know how its working, project still WIP
